### ISSUE TITLE
4-refactoring - smelly_podcast doesn't run

### ISSUE THREAD

**Issue by rbmisc** [talkpython/mastering-pycharm-course#31]
I have downloaded the 4-refactoring for Your turn: Refactoring.
I am getting following when I run it.

```
Welcome to the talk python info downloader.

Traceback (most recent call last):
  File "/Desktop/mastering-pycharm-course/mastering-pycharm-course/your-turn/4-refactoring/smelly_podcast/program.py", line 56, in <module>
    main()
  File "/Desktop/mastering-pycharm-course/mastering-pycharm-course/your-turn/4-refactoring/smelly_podcast/program.py", line 41, in main
    end = random.randint(130, latest_id + 1)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/random.py", line 248, in randint
    return self.randrange(a, b+1)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/random.py", line 226, in randrange
    raise ValueError("empty range for randrange() (%d, %d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (130, 27, -103)
Working with total of 25 episodes

Process finished with exit code 1
```

The Python version I have in the virtual environment is 3.8.2 and I have version 2020.1.1 Professional Edition on an iMac with macOS Catalina.

**Comment by mikeckennedy** [comment]
Hi @rbmisc Sorry about that. We had to change the RSS feed and apparently this wasn't able to handle it. Just committed a quick fix:

https://github.com/talkpython/mastering-pycharm-course/commit/79d0b8bce5dc7ed7a7356ca67a3b715e5d79017a

**Comment by mikeckennedy** [comment]
@rbmisc Thanks for letting me know this was an issue.
